### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tomphilbin** [prettier/prettier-logo#2]
Hey,

To ensure that we can use these logos (great job btw) in the community, would it be possible to add a license to this repo please?

Cheers! 

Tom

**Comment by ianstormtaylor** [comment]
cc @vjeux @jlongster, feel free to add whatever license you want to this to match existing prettier stuff if you want! Or let me know if you need me.

**Comment by vjeux** [comment]
@ianstormtaylor sounds good, I just added the LICENSE file from the prettier repo. Thanks again for the logo, it's seriously awesome :)
